### ISSUE TITLE
status

### ISSUE THREAD

**Issue by thaonguyenle** [eddiejibson/chae#2]
Hello again,

https://chae.sh/thaonguyenle.id

Underneath my name says: I haven't a chae status, yet.

But I can't find a place where I can update my status

**Comment by eddiejibson** [comment]
Hi 👋 

You can update it in the [options tab](https://chae.sh/options).

I'll release a new patch so on a user's profile it will note to the user that they should visit this page if they'd like it updated.

Let me know if you have any more issues.

Cheers.
@thaonguyenle
