### ISSUE TITLE
Typos on homepage

### ISSUE THREAD

**Issue by lizblockstack** [eddiejibson/chae#3]
Hi! Neat app! I saw a few typos on the homepage:

![image](https://user-images.githubusercontent.com/39883666/51333883-a9cafd00-1a4c-11e9-89ec-fb5c92d9100c.png)

"indivuals" to individuals

"corporation's" to corporations

Congrats though!

**Comment by eddiejibson** [comment]
Hi @lizblockstack,

I'll fix that right away! Terribly sorry for this, I rushed to have something quick written up 😄 

Thanks for letting me know.

**Comment by lizblockstack** [comment]
No worries! Nice job. I think "simplistic" should also be "simple" no?

**Comment by eddiejibson** [comment]
Oh, yeah. I'll fix that, too.

Thanks again 🙏

**Comment by eddiejibson** [comment]
Fixed and pushed 😄
