### ISSUE TITLE
Suggestion: Push the copyright angle

### ISSUE THREAD

**Issue by moxiegirl** [eddiejibson/chae#4]
While I like the "your in control of your data" I think a more specific issue is copyright. Many people don't realize the blog sites own or can use their content. I presume this is not possible with yours. So rather than say "own your data" you might want to say: "own your content entirely" and maybe have a page on your site that explains the copyright issue with sites like Medium or Linkedin.

https://lifehacker.com/whats-with-new-blogging-platforms-like-medium-should-1518292181

> Lastly, these platforms have one other big problem: With Medium, you give them royalty-free access to your content. You still own the copyright to your words, but they can do whatever they want with what you write (you can always delete your blogs, but that kind of defeats the point). That means they can sell a blog post, use it for an ad, or anything else, without paying you for your work. They don't seem to ever sell posts, but the the point is they could. Our own Kinja's Terms of Use also has monetization options, but it's more clear on the role advertising plays, and how Kinja users and editors can use your content. Conversely, if Svbtle has a Terms of Service, I can't find it anywhere, so it's not clear who owns your posts.

**Comment by eddiejibson** [comment]
Hi @moxiegirl,

Thanks for the idea! I agree completely with you. But, yes, the user owns the data entirely so I'll make that a lot more apparent with a bit more of a detailed explanation.

Let me know if you have any more suggestions :)
